### ISSUE TITLE
Store unprocessed transaction ids in database

### ISSUE THREAD

**Issue by jorian** [verus-discord-bot/bot#43]
Whenever the bot has deposits disabled, the pending transactions are put in a runtime queue. 

It would be nice to have a cache in the database that stores these transactions in order to process them whenever the bot restarts.

**Comment by Oink70** [comment]
A field specifying the blockheight when going in maintenance, combined with a rescan from that height when disabling maintenance mode would (IMHO) be the most efficient procedure for that.

**Comment by jorian** [comment]
fixed by 428710c
